function renderAgenda(){
  const y=currentMonth.getFullYear(),m=currentMonth.getMonth(); $('#content').innerHTML=`${pageHead('Planner','Visitas de orçamento, obras e compromissos em um só calendário.',`<button class="btn-primary" id="newEvent">+ Agendar</button>`)}<div class="panel calendar-panel"><div class="calendar-head"><div class="calendar-nav"><button class="icon-btn" id="prevMonth">←</button><button class="icon-btn" id="todayMonth">Hoje</button><button class="icon-btn" id="nextMonth">→</button></div><h2>${currentMonth.toLocaleDateString('pt-BR',{month:'long',year:'numeric'})}</h2><span></span></div><div class="cal-grid">${calendarHTML(y,m)}</div></div>`;
  $('#newEvent').onclick=()=>openAgendaModal(); $('#prevMonth').onclick=()=>{currentMonth=new Date(y,m-1,1);renderAgenda();};$('#nextMonth').onclick=()=>{currentMonth=new Date(y,m+1,1);renderAgenda();};$('#todayMonth').onclick=()=>{currentMonth=new Date();renderAgenda();};$$('[data-cal-event]').forEach(b=>b.onclick=()=>{const a=state.gestao.agenda.find(x=>x.id===b.dataset.calEvent); if(a)openAgendaModal(a.id);else if(b.dataset.workId)openWorkModal(b.dataset.workId);});$$('[data-cal-day]').forEach(d=>d.ondblclick=()=>openAgendaModal('',d.dataset.calDay));
}
function calendarHTML(y,m){
  const first=new Date(y,m,1),start=new Date(y,m,1-first.getDay()),today=isoToday(); let html=['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'].map(d=>`<div class="cal-weekday">${d}</div>`).join(''); for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const iso=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;const ev=state.gestao.agenda.filter(a=>a.data===iso).map(a=>({...a,_source:'agenda'})); const works=state.gestao.obras.filter(w=>w.inicio===iso||w.fim===iso).map(w=>({id:`work_${w.id}`,tipo:'obra',titulo:`${w.inicio===iso?'Início':'Fim'}: ${w.titulo||'Obra'}`,obraId:w.id,_source:'work'})); html+=`<div class="cal-day ${d.getMonth()!==m?'out':''} ${iso===today?'today':''}" data-cal-day="${iso}"><div class="daynum">${d.getDate()}</div>${[...ev,...works].slice(0,5).map(e=>`<button class="cal-event ${e.tipo||'outro'}" ${e._source==='agenda'?`data-cal-event="${e.id}"`:`data-cal-event="x" data-work-id="${e.obraId}"`} title="${esc(e.titulo)}">${esc(e.hora?`${e.hora} ${e.titulo}`:e.titulo)}</button>`).join('')}</div>`;}return html;
}
function openAgendaModal(id='',presetDate=''){
  const a=id?state.gestao.agenda.find(x=>x.id===id):{tipo:'orcamento',clienteId:'',titulo:'',data:presetDate||isoToday(),hora:'09:00',fim:'',funcionarios:[],status:'pendente',observacoes:''};
  modal(id?'Editar compromisso':'Novo compromisso',`<form id="agendaForm"><div class="form-grid"><div class="field"><label>Tipo</label><select name="tipo"><option value="orcamento" ${a.tipo==='orcamento'?'selected':''}>Orçamento / visita</option><option value="obra" ${a.tipo==='obra'?'selected':''}>Obra / serviço</option><option value="outro" ${a.tipo==='outro'?'selected':''}>Outro</option></select></div><div class="field"><label>Cliente</label><select name="clienteId"><option value="">Sem cliente</option>${state.gestao.clientes.map(c=>`<option value="${c.id}" ${a.clienteId===c.id?'selected':''}>${esc(c.nome)}</option>`).join('')}</select></div><div class="field full"><label>Título *</label><input name="titulo" value="${esc(a.titulo)}" required placeholder="Ex.: Medir sala para orçamento"></div><div class="field"><label>Data *</label><input name="data" type="date" value="${esc(a.data)}" required></div><div class="field"><label>Hora</label><input name="hora" type="time" value="${esc(a.hora)}"></div><div class="field"><label>Fim (opcional)</label><input name="fim" type="time" value="${esc(a.fim)}"></div><div class="field"><label>Status</label><select name="status"><option value="pendente" ${a.status==='pendente'?'selected':''}>Pendente</option><option value="concluido" ${a.status==='concluido'?'selected':''}>Concluído</option><option value="cancelado" ${a.status==='cancelado'?'selected':''}>Cancelado</option></select></div><div class="field full"><label>Funcionários</label><div class="checks">${staffChecks(a.funcionarios||[])||'<span class="cell-sub">Nenhum funcionário cadastrado.</span>'}</div></div><div class="field full"><label>Observações</label><textarea name="observacoes">${esc(a.observacoes)}</textarea></div></div></form>`,{saveText:'Salvar compromisso',extra:id?`<button class="btn-red" id="deleteEvent">Excluir</button>`:'',onSave:async()=>{const f=$('#agendaForm');if(!f.reportValidity())return false;const staff=$$('input[name="staff"]:checked',f).map(x=>x.value); if(hasAgendaConflict(f.data.value,f.hora.value,staff,id)){if(!confirm('Existe funcionário já agendado nesse mesmo horário. Salvar mesmo assim?'))return false;}const obj={...a,id:a.id||uid('age'),tipo:f.tipo.value,clienteId:f.clienteId.value,titulo:f.titulo.value.trim(),data:f.data.value,hora:f.hora.value,fim:f.fim.value,funcionarios:staff,status:f.status.value,observacoes:f.observacoes.value.trim()};if(id)state.gestao.agenda[state.gestao.agenda.findIndex(x=>x.id===id)]=obj;else state.gestao.agenda.push(obj);await saveGestao('Compromisso salvo.');renderSection('agenda');return true;}}); if(id)$('#deleteEvent').onclick=async()=>{if(!confirm('Excluir este compromisso?'))return;state.gestao.agenda=state.gestao.agenda.filter(x=>x.id!==id);await saveGestao('Compromisso excluído.');closeModal();renderSection('agenda');};
}
function hasAgendaConflict(data,hora,staff,ignore=''){if(!staff.length)return false;return state.gestao.agenda.some(a=>a.id!==ignore&&a.data===data&&(!hora||!a.hora||a.hora===hora)&&(a.funcionarios||[]).some(id=>staff.includes(id)));}

function renderObras(){
  $('#content').innerHTML=`${pageHead('Obras','Planeje datas, equipe e andamento dos serviços aprovados.',`<button class="btn-primary" id="newWork">+ Nova obra</button>`)}<div class="panel"><div class="searchbar"><input id="workSearch" placeholder="Buscar por cliente, obra, funcionário ou status..."></div><div id="workList"></div></div>`;$('#newWork').onclick=()=>openWorkModal();$('#workSearch').oninput=renderWorkList;renderWorkList();
}
function renderWorkList(){const box=$('#workList');if(!box)return;const q=normalize($('#workSearch')?.value);let works=[...state.gestao.obras].sort((a,b)=>String(b.inicio||'').localeCompare(String(a.inicio||'')));if(q)works=works.filter(w=>normalize(`${w.titulo} ${w.status} ${getClient(w.clienteId)?.nome} ${(w.funcionarios||[]).map(id=>getStaff(id)?.nome).join(' ')}`).includes(q));if(!works.length){box.innerHTML='<div class="empty">Nenhuma obra cadastrada.</div>';return;}box.innerHTML=works.map(w=>`<div class="work-card"><div class="work-top"><div><h3>${esc(w.titulo||'Obra')}</h3><div class="cell-sub">${esc(getClient(w.clienteId)?.nome||'Cliente removido')} • ${formatDate(w.inicio)} até ${formatDate(w.fim)}</div></div><span class="chip ${w.status}">${statusLabel(w.status)}</span></div><div class="work-meta"><span>💰 ${brl(w.valor||0)}</span><span>👷 ${(w.funcionarios||[]).map(id=>esc(getStaff(id)?.nome)).filter(Boolean).join(', ')||'Equipe não definida'}</span>${w.observacoes?`<span>📝 ${esc(w.observacoes)}</span>`:''}</div><div class="actions" style="margin-top:12px"><button class="icon-btn" data-edit-work="${w.id}">Editar</button>${w.status==='agendado'?`<button class="icon-btn ok" data-start-work="${w.id}">Iniciar obra</button>`:''}${w.status==='em-andamento'?`<button class="icon-btn ok" data-finish-work="${w.id}">Concluir</button>`:''}<button class="icon-btn del" data-del-work="${w.id}">Excluir</button></div></div>`).join('');$$('[data-edit-work]').forEach(b=>b.onclick=()=>openWorkModal(b.dataset.editWork));$$('[data-start-work]').forEach(b=>b.onclick=()=>changeWorkStatus(b.dataset.startWork,'em-andamento'));$$('[data-finish-work]').forEach(b=>b.onclick=()=>changeWorkStatus(b.dataset.finishWork,'concluida'));$$('[data-del-work]').forEach(b=>b.onclick=()=>deleteWork(b.dataset.delWork));}
function staffChecks(selected=[]){return state.gestao.funcionarios.filter(f=>f.ativo!==false).map(f=>`<label class="check"><input type="checkbox" name="staff" value="${f.id}" ${selected.includes(f.id)?'checked':''}> ${esc(f.nome)}${f.funcao?` • ${esc(f.funcao)}`:''}</label>`).join('');}
function openWorkModal(id='',quoteId=''){
  const q=quoteId?getQuote(quoteId):null; const w=id?getWork(id):{orcamentoId:q?.id||'',clienteId:q?.clienteId||'',titulo:q?.titulo||'',status:'agendado',inicio:'',fim:'',funcionarios:[],valor:q?quoteTotal(q):0,observacoes:q?.observacoes||''}; if(!state.gestao.clientes.length){toast('Cadastre um cliente antes de criar uma obra.','err');return;}
  modal(id?'Editar obra':'Nova obra',`<form id="workForm"><div class="form-grid"><div class="field"><label>Cliente *</label><select name="clienteId" required><option value="">Selecione</option>${state.gestao.clientes.map(c=>`<option value="${c.id}" ${w.clienteId===c.id?'selected':''}>${esc(c.nome)}</option>`).join('')}</select></div><div class="field"><label>Orçamento vinculado</label><select name="orcamentoId"><option value="">Sem vínculo</option>${state.gestao.orcamentos.filter(o=>o.status==='aprovado'||o.id===w.orcamentoId).map(o=>`<option value="${o.id}" ${w.orcamentoId===o.id?'selected':''}>${esc(o.numero)} — ${esc(getClient(o.clienteId)?.nome||'')}</option>`).join('')}</select></div><div class="field full"><label>Nome da obra *</label><input name="titulo" value="${esc(w.titulo)}" required placeholder="Ex.: Forro e sanca — Sala"></div><div class="field"><label>Início *</label><input name="inicio" type="date" value="${esc(w.inicio)}" required></div><div class="field"><label>Previsão de término</label><input name="fim" type="date" value="${esc(w.fim)}"></div><div class="field"><label>Status</label><select name="status">${['agendado','em-andamento','concluida','cancelada'].map(s=>`<option value="${s}" ${w.status===s?'selected':''}>${statusLabel(s)}</option>`).join('')}</select></div><div class="field"><label>Valor</label><input name="valor" type="number" min="0" step="0.01" value="${Number(w.valor||0)}"></div><div class="field full"><label>Equipe responsável</label><div class="checks">${staffChecks(w.funcionarios||[])||'<span class="cell-sub">Cadastre funcionários para montar a equipe.</span>'}</div></div><div class="field full"><label>Observações</label><textarea name="observacoes">${esc(w.observacoes)}</textarea></div></div></form>`,{saveText:'Salvar obra',onSave:async()=>{const f=$('#workForm');if(!f.reportValidity())return false;const staff=$$('input[name="staff"]:checked',f).map(x=>x.value);if(f.fim.value&&f.fim.value<f.inicio.value){toast('A data de término não pode ser anterior ao início.','err');return false;}const conflicts=workConflicts(f.inicio.value,f.fim.value||f.inicio.value,staff,id);if(conflicts.length&&!confirm(`Atenção: ${conflicts.join(', ')} já está(ão) alocado(s) em outra obra nesse período. Salvar mesmo assim?`))return false;const obj={...w,id:w.id||uid('obra'),orcamentoId:f.orcamentoId.value,clienteId:f.clienteId.value,titulo:f.titulo.value.trim(),status:f.status.value,inicio:f.inicio.value,fim:f.fim.value,funcionarios:staff,valor:Number(f.valor.value||0),observacoes:f.observacoes.value.trim(),criadoEm:w.criadoEm||isoToday()};if(id)state.gestao.obras[state.gestao.obras.findIndex(x=>x.id===id)]=obj;else state.gestao.obras.push(obj);if(obj.orcamentoId){const oq=getQuote(obj.orcamentoId);if(oq&&oq.status!=='aprovado'){oq.status='aprovado';oq.aprovadoEm=isoToday();}}await saveGestao('Obra salva.');renderSection('obras');return true;}});
  const form=$('#workForm'); form.orcamentoId.onchange=()=>{const oq=getQuote(form.orcamentoId.value);if(oq){form.clienteId.value=oq.clienteId;form.titulo.value=oq.titulo;form.valor.value=quoteTotal(oq);}};
}
function workConflicts(start,end,staff,ignore=''){if(!staff.length)return[];const ids=new Set();state.gestao.obras.filter(w=>w.id!==ignore&&!['concluida','cancelada'].includes(w.status)&&overlap(start,end,w.inicio,w.fim||w.inicio)).forEach(w=>(w.funcionarios||[]).forEach(id=>{if(staff.includes(id))ids.add(id)}));return [...ids].map(id=>getStaff(id)?.nome).filter(Boolean);}
async function changeWorkStatus(id,status){const w=getWork(id);if(!w)return;w.status=status;await saveGestao(`Obra marcada como ${statusLabel(status).toLowerCase()}.`);renderWorkList();}
async function deleteWork(id){if(!confirm('Excluir esta obra?'))return;state.gestao.obras=state.gestao.obras.filter(w=>w.id!==id);state.gestao.agenda=state.gestao.agenda.filter(a=>a.obraId!==id);await saveGestao('Obra excluída.');renderWorkList();}

