let siteTab='dados';
function renderSite(){
  $('#content').innerHTML=`${pageHead('Editar site','Conteúdo público do ferrarigesso.com.br.')}<div class="panel"><div class="notice">As alterações desta área mudam o site público. O sistema de clientes, orçamentos e obras fica separado desses dados.</div><div class="site-tabs">${[['dados','Dados e textos'],['carrossel','Carrossel'],['servicos','Serviços'],['galeria','Galeria']].map(([id,t])=>`<button class="site-tab ${siteTab===id?'active':''}" data-site-tab="${id}">${t}</button>`).join('')}</div><div id="siteEditor"></div><div class="savebar"><button class="btn-green" id="saveSite">SALVAR ALTERAÇÕES DO SITE</button></div></div>`;
  $$('[data-site-tab]').forEach(b=>b.onclick=()=>{siteTab=b.dataset.siteTab;renderSite();});$('#saveSite').onclick=saveSite;renderSiteTab();
}
function renderSiteTab(){const e=$('#siteEditor');if(!e)return;if(siteTab==='dados'){const d=state.site.dados;e.innerHTML=`<div class="form-grid">${siteInput('whatsapp','WhatsApp com DDI e DDD',d.whatsapp)}${siteInput('telefoneExibido','Telefone exibido',d.telefoneExibido)}${siteInput('cidade','Cidade / região',d.cidade)}${siteInput('instagram','Instagram',d.instagram)}${siteInput('facebook','Facebook',d.facebook)}${siteInput('tag','Tag da capa',d.tag)}${siteInput('heroTitulo','Título da capa',d.heroTitulo,true)}${siteInput('heroDescricao','Descrição da capa',d.heroDescricao,true)}${siteInput('botaoOrcamento','Texto do botão',d.botaoOrcamento)}${siteInput('sobreTitulo','Título Sobre',d.sobreTitulo)}${siteArea('sobreTexto','Texto Sobre',d.sobreTexto)}${siteInput('contatoTitulo','Título Contato',d.contatoTitulo)}${siteArea('contatoDescricao','Descrição Contato',d.contatoDescricao)}${siteInput('footerTexto','Texto do rodapé',d.footerTexto,true)}</div>`;$$('[data-site-key]').forEach(i=>i.oninput=()=>state.site.dados[i.dataset.siteKey]=i.value);return;}const arr=state.site[siteTab]||[];if(siteTab==='servicos'){e.innerHTML=`<div class="service-grid">${arr.map((x,i)=>`<div class="media-card"><img id="siteImg-${siteTab}-${i}" src="${esc(x.imagem||'')}" alt=""><div class="pad"><div class="field"><label>Nome</label><input data-svc-title="${i}" value="${esc(x.titulo||'')}"></div><div class="field"><label>Descrição</label><textarea data-svc-desc="${i}">${esc(x.descricao||'')}</textarea></div>${mediaPicker(siteTab,i)}</div></div>`).join('')}</div>`;$$('[data-svc-title]').forEach(i=>i.oninput=()=>state.site.servicos[+i.dataset.svcTitle].titulo=i.value);$$('[data-svc-desc]').forEach(i=>i.oninput=()=>state.site.servicos[+i.dataset.svcDesc].descricao=i.value);bindMediaPickers();return;}e.innerHTML=`<div class="media-grid">${arr.map((x,i)=>`<div class="media-card"><img id="siteImg-${siteTab}-${i}" src="${esc(x.imagem||'')}" alt=""><div class="pad"><b>${siteTab==='carrossel'?'Slide':'Foto'} ${i+1}</b>${mediaPicker(siteTab,i)}</div></div>`).join('')}</div>`;bindMediaPickers();}
function siteInput(k,l,v,full=false){return `<div class="field ${full?'full':''}"><label>${l}</label><input data-site-key="${k}" value="${esc(v||'')}"></div>`;}function siteArea(k,l,v){return `<div class="field full"><label>${l}</label><textarea data-site-key="${k}">${esc(v||'')}</textarea></div>`;}function mediaPicker(kind,i){return `<label class="btn" style="display:inline-block;margin-top:9px">Escolher imagem<input hidden type="file" accept="image/*" data-media="${kind}:${i}"></label>`;}
function bindMediaPickers(){$$('[data-media]').forEach(inp=>inp.onchange=async()=>{const file=inp.files?.[0];if(!file)return;if(!file.type.startsWith('image/')){toast('Escolha uma imagem válida.','err');return;}if(file.size>12*1024*1024){toast('Imagem muito grande. Use até 12 MB.','err');return;}try{toast('Preparando imagem…');const data=await compressFile(file);const [kind,idx]=inp.dataset.media.split(':');state.site[kind][+idx].imagem=data;const im=$(`#siteImg-${kind}-${idx}`);if(im)im.src=data;toast('Imagem pronta. Clique em salvar alterações do site.','ok');}catch{toast('Não foi possível processar a imagem.','err');}});}
function compressFile(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{try{const MAX=1400,k=Math.min(1,MAX/Math.max(im.width,im.height)),w=Math.round(im.width*k),h=Math.round(im.height*k),c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(im,0,0,w,h);let q=.78,data=c.toDataURL('image/jpeg',q);while(data.length>850000&&q>.4){q-=.08;data=c.toDataURL('image/jpeg',q);}resolve(data);}catch(e){reject(e)}};im.onerror=reject;im.src=r.result};r.onerror=reject;r.readAsDataURL(file)});}
async function publishPendingMedia(){const jobs=[];for(const kind of ['carrossel','servicos','galeria'])for(let i=0;i<(state.site[kind]||[]).length;i++){const item=state.site[kind][i],im=item?.imagem;if(im?.startsWith('data:')){const id=`${kind}-${i}`;jobs.push(setDoc(doc(db,'sites',SITE_ID,'midias',id),{dataUrl:im,atualizadoEm:serverTimestamp()}).then(()=>item.imagem=`midia:${id}`));}}await Promise.all(jobs);}
async function resolveAllMedia(){const jobs=[];for(const kind of ['carrossel','servicos','galeria'])for(let i=0;i<(state.site[kind]||[]).length;i++){const item=state.site[kind][i],im=item?.imagem;if(im?.startsWith('midia:')){const id=im.slice(6);jobs.push(getDoc(doc(db,'sites',SITE_ID,'midias',id)).then(s=>{if(s.exists()&&s.data().dataUrl)item.imagem=s.data().dataUrl;}).catch(()=>{}));}}await Promise.all(jobs);}

